### PR TITLE
physica: further reduction in text, split math & physics parts

### PR DESCRIPTION
**Pull request by Leedehai**
Hi, on my [physica](https://github.com/Leedehai/typst-physics/blob/master/physica-manual.pdf) package:

I heeded your earlier advice and decided to take the initiative and reduce the text body, so you don't have to put efforts in extracting the essential parts :) The math.md document's length is reduced _to_ 1/4 of the original. Hope you like it.

(also: I'm working on adding the [ctheorems](https://github.com/typst/packages/tree/main/packages/preview/ctheorems) (originally named "theorems": [repo](https://github.com/sahasatvik/typst-theorems)) package to math.md, and that PR will need to based on this PR's branch.)

### CODE REVIEW

**Comment by Leedehai** [comment]
By the way there seems to be an issue, so I did not add `a iprod b` to the entry that shows `dprod` and `cprod`:
```
#import "@preview/physica:0.9.1": iprod

$ iprod(u, v) $
```

It is okay in the Typst web app (compiler version is "Latest" i.e. 0.10.0):

But in typst-examples-book's local serve `mdbook serve` it becomes:

**Comment by sitandr** [comment]
> But in typst-examples-book's local serve mdbook serve it becomes:

I tried pasting this example into my local book, and it rendered fine. I think the problem might be related to your local setup, maybe unreleased version of compiler or bad package files. I think we could try adding this to the book and see what happens.
image

**Comment by sitandr** [comment]
Another comment. This is far from being important, many of my examples don't follow that rule.

However, I think it would be better to use smaller examples where possible. It is hard to "go to source", so rendered image and source code should be as close as possible.

In general, the size if fine, but I suppose it could be better to split it into two smaller examples.

image

**Comment by sitandr** [comment]
I splitted them and added `iprod`. Feel free to revert if you think this is inappropriate. 

I can merge it now, if there is nothing else you want to add.

**Comment by Leedehai** [comment]
Thanks! Let me make some further edits to group the split tables in a better way, and I'll upload a new commit later.

**Comment by Leedehai** [comment]
Okay, I'm done :)

**Pull request merged**
